ttdp_talent_capability:
  outputs:
    dev:
      dataset: test
      job_execution_timeout_seconds: 300
      job_retries: 1
      method: oauth
      location: US
      priority: interactive
      project: tw-empo-twer-growth-dp-dev
      threads: 1
      type: bigquery
    prod:
      dataset: test
      job_execution_timeout_seconds: 300
      job_retries: 1
      method: oauth
      location: US
      priority: interactive
      project: tw-empo-twer-growth-dp-prod
      threads: 1
      type: bigquery
  target: dev
